### ISSUE TITLE
How to submit tests

### ISSUE THREAD

**Issue by pasumps1** [ModernAppsNinja/vspheretanzu101_vt7301#1185]
still i am facing some issues when i try to get the completion certificate. I am not aware where i have to check

**Comment by Moezenka** [comment]
Hmm i experienced some issues also but in my case i forgot to enroll for the course.

Did you enroll yet?

**Comment by afewell** [comment]
I am closing this issue as I resolved this in separate conversations for the associated pull requests.

**Comment by afewell** [comment]
@Moezenka thanks for your assist! That qualifies you for the hackathon support provider badge if you would like to request it via the instructions on the hackathon site. Thanks!
