### ISSUE TITLE
The Big Picture - VSphere

### ISSUE THREAD

**Issue by Lacoste** [ModernAppsNinja/vspheretanzu101_vt7301#160]
Shouldn't all these 'VSphere' named sections be 'vSphere'?
Ref: https://www.vmware.com/products/vsphere/vsphere-with-tanzu.html

**Comment by pescerosso** [comment]
Yes but the template doesn't allow lower letters at the beginning of the sentence

**Comment by pescerosso** [comment]
Thanks, for reporting I fixed them.

**Comment by pescerosso** [comment]
Thanks, for reporting I fixed them.
