### ISSUE TITLE
Section 3 Test

### ISSUE THREAD

**Issue by linuxtek-canada** [ModernAppsNinja/vspheretanzu101_vt7301#529]
Some questions around this test.  Please check to make sure the source material covers the questions that are on the test.

1.  From the videos, Workload Management needs to be enabled, then the Tanzu Kubernetes Grid installer needs to be run to install TKG.  So the correct answer would be A.

2.  I don't believe any of the videos or documents in this section went over this.  I had to Google for this page to find the answer:
https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.0/vmware-tanzu-kubernetes-grid-10/GUID-tanzu-k8s-clusters-create.html#:~:text=To%20deploy%20a%20Tanzu%20Kubernetes%20cluster%20with%20the%20minimum%20default,the%20%2D%2Dplan%3Ddev%20option.&text=This%20command%20deploys%20a%20Tanzu,this%20Tanzu%20Kubernetes%20Grid%20release.

4.  I don't believe this software for data protection was discussed in the section either.  I had to find this page to look for an answer:
https://docs.vmware.com/en/VMware-Tanzu-Mission-Control/services/tanzumc-concepts/GUID-C16557BC-EB1B-4414-8E63-28AD92E0CAE5.html

5.  Again, I don't believe this was discussed in the modules.  I had to search to find this for the answer:
https://cluster-api.sigs.k8s.io/

**Comment by afewell** [comment]
Hi @linuxtek-canada this question may be a bit tricky, vSphere 7 with Tanzu does not have anything called the Tanzu Kubernetes Grid installer, there is sort of a wizard but all of the files needed to enable Tanzu are already present in vCenter to enable the feature. I do get this may be tricky, but it is a free open book test that you can take as many times as you would like, and I dont think this question is any more tricky than many questions you find on most exams you have to pay to sit once that are closed book. Even if you were unsure about answer a., I feel like answer b is a true statement, and the question itself just asks which is the most correct statement, it doesnt ask how to install. So I think its a fair question, but I will mark it for review and team discussion at the next course update. I really do appreciate your thoughtful discussion on the topic, that attention to detail and level of caring about it I think says a lot about your character and attention to detail, very well done.
