### ISSUE TITLE
Unable to submit test answers

### ISSUE THREAD

**Issue by arunsd27** [ModernAppsNinja/vspheretanzu101_vt7301#977]
**Describe the bug**

I followed the instructions to register for the course and on submitting test answers, i'm getting error that you need to enroll for the course.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by afewell** [comment]
Hi @arunsd27 I am not sure what you ran into, but as of now it looks like your member page has a course record and shows that you have taken test1: [https://github.com/modernappsninjas/arunsd27/blob/main/content/english/course/vspheretanzu101_vt7301.md](https://github.com/modernappsninjas/arunsd27/blob/main/content/english/course/vspheretanzu101_vt7301.md). I didnt see any attempts for test2 from you yet so hopefully whatever problem there may have been has worked itself out, please try to take test2 again and let me know if you run into any further issues. Thanks!

**Comment by arunsd27** [comment]
Thank you, yes the registration completed successfully. Sorry, i was trying in a wrong branch.
