### ISSUE TITLE
Cloud Native Infrastructure Requirements

### ISSUE THREAD

**Issue by khemdev2005** [ModernAppsNinja/vspheretanzu101_vt7301#978]
vSphere with Tanzu 101, lesson, VMware with Tanzu Whiteboard throws the following error:
Here is the url giving the below error:
https://modernapps.ninja/vspheretanzu101_vt7301/docs/thebigpicture/vspherewithtanzuwhiteboard/

Error 503 Service Unavailable

Service Unavailable
Guru Mediation:

Details: cache-lga21940-LGA 1623146624 847850240

Varnish cache server

**Comment by afewell** [comment]
I heard there was an error with one of the big content delivery networks that was impacting availability of github itself and of course our stuff so I think this may have been a temporary issue. If you do have problems accessing the video through the site, you can access this video directly on the ModernApps learning page on youtube at :https://www.youtube.com/watch?v=d6Hc2ceghIk&t=5s
Thank you!
